version: '3.8'

services:

    #PHP Service
    app:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                user: 1000
                uid: 1000
        container_name: app
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - app-network

    #Nginx Service
    webserver:
        image: nginx:alpine
        container_name: webserver
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network

    #MySQL Service
    db:
        image: mysql:8.0.25
        container_name: db
        restart: unless-stopped
        tty: true
        ports:
            - "3307:3306"
        expose:
            - "3307"
        environment:
            MYSQL_DATABASE: vacations
            MYSQL_USER: laraveluser
            MYSQL_PASSWORD: 123456
            MYSQL_ROOT_PASSWORD: 123456
        volumes:
            - dbdata:/var/lib/mysql/
        networks:
            - app-network

#Docker Networks
networks:
    app-network:
        driver: bridge
#Volumes
volumes:
    dbdata:
        driver: local
